[aTable] allow user to move table rows
agritheory/stonecrop pull request #126
Opened 2024-05-07 12:36 UTC by bhattdevarsh

2024-05-07 12:38 UTC, bhattdevarsh commented
The Table rows are draggable as required, but the feature is not complete yet:

After the drag event, the table row is being placed correctly and sorting it as intended, but the `tableData` is getting refreshed due to which it appear as it is not doing anything, attaching video which demonstrate row 1 moved to row 10 and rows between 2-9 are shifting 1 row above and then the table data is refreshing itself in console log.

https://github.com/agritheory/stonecrop/assets/58166671/d4ad223a-2a07-407f-b408-c7ad0b5d4fa6

2024-05-07 12:44 UTC, agritheory commented
@bhattdevarsh This is not the feature associated with #49 which was intended to be able to resize columns. That said, this is a nice-to-have, so I suspect we'll end up completing it but associated with another ticket.

2024-05-24 10:48 UTC, Alchez requested changes
@bhattdevarsh I tried the following methods locally to update the table but with no luck:
- Using a `key` attribute on the `ARow` and `ATable` top-level elements (via an emit) to [force a re-render](https://blog.logrocket.com/correctly-force-vue-component-re-render/#key-changing-technique) whenever a re-arrange occurred.
- Manually calling `forceUpdate` on the Vue component, but that didn't help either.

2024-05-24 10:48 UTC, Alchez commented on atable/src/components/ARow.vue
> +	initialValue: { x: 5, y: (props.rowIndex + 1) * 21 },
Don't use [magic numbers](https://en.wikipedia.org/wiki/Magic_number_(programming)). Is the `21` supposed to be the row height? Can we compute it instead?

2024-05-24 10:48 UTC, Alchez commented on atable/src/components/ARow.vue
> +const { x, y, style } = useDraggable(rowEl, {
Without passing a `containerElement`, I think the composable is letting you drag the row outside the bounds of the table, which is causing some issues with the row data (random `undefined` rows)

2025-07-25 08:51 UTC, closed without merging

2025-07-25 08:51 UTC, Alchez commented
Closing in favour of #277, since I can't push changes here