added DayDivider to Beam
agritheory/stonecrop pull request #180
Opened 2024-11-04 16:52 UTC by crabinak

@agritheory 
I've added a DayDivider to the Beam ListView. I centered-aligned the text to help it visually stand out amongst the lists. The medium gray worked best here as the darker colors overpowered the navigation menu. This takes in month, day, and year as props and formats them to display, but it could be reworked to take in an object or however the date would be passed in.

2024-11-06 14:28 UTC, agritheory requested changes
I'd like to see the specimen use the ListView component API, I left an example that works but  doesn't look right

![image](https://github.com/user-attachments/assets/cccb5ff4-72fb-49aa-bcda-68355e54cba1)

2024-11-06 14:28 UTC, agritheory commented on examples/beam/default.story.vue
> +			<BeamDayDivider :month="'10'" :day="'20'" :year="'2024'" />
Something like this but perhaps with a pre-formatted date. 

```const itemsWithDayDivider = computed(() => {
	items.splice(5, 0, {
			label: new Date(),
			linkComponent: 'DayDivider',
		})
	return items
})```

2024-11-07 10:26 UTC, Alchez commented
@crabinak I've added a commit that merges changes from the main branch, so you will have to pull before making more changes.

2024-11-25 15:51 UTC, crabinak commented
@agritheory I updated this to use linkComponent. It accepts a Date object as the prop as well as an option to specify the format. As an example, I provided two date dividers: one as the default DateString and the other using ISOString. I didn't add more format types just incase this feature was not desired. 

I also left-aligned the DayeDivider content as having it center-aligned made it stand out but not in a good way.

2024-11-26 11:31 UTC, Alchez commented
@agritheory @crabinak 

I added some minor processing changes, and here's what the latest iteration looks like:

![image](https://github.com/user-attachments/assets/5bd0826a-ec2c-4512-8b4a-2db6f48b7b55)

Let me know if that looks okay.

2024-11-26 13:26 UTC, agritheory commented
@crabinak @Alchez How do we feel about using the lighter blue "cell change color" as background for this?

2024-11-26 15:48 UTC, crabinak commented
@Alchez Looks good to me. 

@agritheory I updated this to use that light blue color you requested. I also removed the top border from the day divider as it was causing a double border with the bottom border from the previous item.

2024-11-27 06:14 UTC, Alchez approved these changes

2024-11-27 12:31 UTC, merged